### ISSUE TITLE
npm run dev  ERROR  Unable to obtain an available random port number!    

### ISSUE THREAD

**Issue by gsshawn** [lianginx/chatgpt-nuxt#3]
ERROR  Unable to obtain an available random port number!                               22:24:24

  at getRandomPort (node_modules/nuxi/dist/chunks/index.mjs:165:11)
  at async findPort (node_modules/nuxi/dist/chunks/index.mjs:236:24)
  at async getPort (node_modules/nuxi/dist/chunks/index.mjs:148:21)
  at async listen (node_modules/nuxi/dist/chunks/index.mjs:704:16)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6773:22)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)

**Comment by lianginx** [comment]
似乎是随机端口有问题的，你可以尝试 `npm run dev --port 4000` 主动指定一个端口

**Comment by lianginx** [comment]
我看了 Nuxt 框架的 Issue，也有人遇到了一样的问题，但我没有找到明确的解决方案
- https://github.com/nuxt/nuxt/issues/19068

**Comment by gsshawn** [comment]
昨天深入的调试了一下，根据大家给出方法，试了一下，先是看了一下版本，之前的node版本低，所以升级了一下，但是还是报错，接着在JSON中指定了端口和IP地址，也还是报错，调试发现拿到hostname不是想要的127.0.0.1，就在host文件中按照，127.0.0.1 XXX，设定了一下，重启项目，终于不报错了，访问时：127.0.0.1:3000，就可以了。
多谢各位。

**Comment by lianginx** [comment]
> 昨天深入的调试了一下，根据大家给出方法，试了一下，先是看了一下版本，之前的node版本低，所以升级了一下，但是还是报错，接着在JSON中指定了端口和IP地址，也还是报错，调试发现拿到hostname不是想要的127.0.0.1，就在host文件中按照，127.0.0.1 XXX，设定了一下，重启项目，终于不报错了，访问时：127.0.0.1:3000，就可以了。 多谢各位。

原来是 Host 的锅，学到了，感谢分享 😃👍🏼
