### ISSUE TITLE
npm i或者npm run dev 提示报错

### ISSUE THREAD

**Issue by torome** [lianginx/chatgpt-nuxt#35]
ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'
Require stack:
- D:\dev\nuxtchat\index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at Function._resolve [as resolve] (node_modules\jiti\dist\jiti.js:1:241025)
  at resolveModule (/D:/dev/nuxtchat/node_modules/@nuxt/kit/dist/index.mjs:2230:29)
  at setup (/D:/dev/nuxtchat/node_modules/@pinia/nuxt/dist/module.mjs:26:60)
  at normalizedModule (/D:/dev/nuxtchat/node_modules/@nuxt/kit/dist/index.mjs:2140:37)
  at async installModule (/D:/dev/nuxtchat/node_modules/@nuxt/kit/dist/index.mjs:2409:95)
  at async initNuxt (/D:/dev/nuxtchat/node_modules/nuxt/dist/index.mjs:3174:7)
  at async load (/D:/dev/nuxtchat/node_modules/nuxi/dist/chunks/dev.mjs:204:9)
  at async Object.invoke (/D:/dev/nuxtchat/node_modules/nuxi/dist/chunks/dev.mjs:248:5)

**Comment by torome** [comment]
搞定了

**Comment by lianginx** [comment]
> 搞定了

是不是手动安装了 Pinia 就搞定了？

**Comment by torome** [comment]
是的，网络上各种试了下
npm install @pinia/nuxt
npm i pinia -f

**Comment by smallfang1111** [comment]
为什么我运行这两个还是报错

![Image](https://github.com/user-attachments/assets/f1516aef-345d-44ec-a88c-a21434ad5778)
